TURRET_UPPER_LIMIT = 100
TURRET_LOWER_LIMIT = -100
TURRET_SLOW_ROTATE_SPEED = 40
TURRET_FAST_ROTATE_SPEED = 100
TURRET_DEAD_ZONE = 5
TURRET_SLOW_ZONE = 10
TURRET_ANGLE_CONVERSION = 1
TURRET_AUTO_POSITION = 50
